export const RESOURCES = {
  RATE: 'rates',
  CDR: 'cdrs',
  AUTH_ORIGIN_TRANSPORT_PROTOCOL: 'auth-orig-transport-protocol',
  ACCOUNTS: 'accounts',
  NETWORKS: 'networks',
  AUTH: 'auth',
  TRANSPORT_PROTOCOLS: 'transport-protocols',
  NETWORK_TYPES: 'network-types',
  ACTIVE_CALLS: 'chart-active-calls',
  ORIGINATED_CPS: 'chart-originated-cps',
  INVOICES: 'invoices',
};

export const SPARSE_FIELDS = {
  [RESOURCES.ACCOUNTS]: 'name',
  [RESOURCES.CDR]: ['time-start',
    'time-connect',
    'time-end',
    'duration',
    'success',
    'src-name-in',
    'src-prefix-in',
    'src-prefix-routing',
    'dst-prefix-in',
    'dst-prefix-routing',
    'lega-disconnect-code',
    'lega-disconnect-reason',
    'destination-initial-rate',
    'destination-next-rate',
    'destination-fee',
    'destination-initial-interval',
    'destination-next-interval',
    'customer-price',
    'auth-orig-ip',
    'auth-orig-port',
    'from-domain',
    'to-domain',
    'ruri-domain',
    'local-tag',
    'auth-orig-transport-protocol'].join(''),
};

export const RELATIONSHIPS = {
  [RESOURCES.AUTH]: {
    login: '',
    password: '',
    jwt: '',
  },
  [RESOURCES.RATE]: {
    prefix: '',
    'initial-rate': '',
    'initial-interval': '',
    'next-rate': '',
    'next-interval': '',
    'connect-fee': '',
    'reject-calls': '',
    'valid-from': '',
    'valid-till': '',
    'network-prefix-id': '',
  },
  [RESOURCES.CDR]: {
    'time-start': '',
    'time-connect': '',
    'time-end': '',
    duration: '',
    success: '',
    'src-name-in': '',
    'src-prefix-in': '',
    'src-prefix-routing': '',
    'dst-prefix-in': '',
    'dst-prefix-routing': '',
    'lega-disconnect-code': '',
    'lega-disconnect-reason': '',
    'destination-initial-rate': '',
    'destination-next-rate': '',
    'destination-fee': '',
    'destination-initial-interval': '',
    'destination-next-interval': '',
    'customer-price': '',
    'auth-orig-ip': '',
    'auth-orig-port': '',
    'from-domain': '',
    'to-domain': '',
    'ruri-domain': '',
    'local-tag': '',
    'auth-orig-transport-protocol': {
      jsonApi: 'hasMany',
    },
    account: {
      jsonApi: 'hasOne',
    },
    // These fields are not used in the table
    'diversion-in': '',
    'lega-rx-payloads': '',
    'lega-tx-payloads': '',
    'auth-orig-transport-protocol-id': '',
    'lega-rx-bytes': '',
    'lega-tx-bytes': '',
    'lega-rx-decode-errs': '',
    'lega-rx-no-buf-errs': '',
    'lega-rx-parse-errs': '',
    'destination-prefix': '',
  },
  [RESOURCES.AUTH_ORIGIN_TRANSPORT_PROTOCOL]: {
    'auth-orig-transport-protocol': 'auth-orig-transport-protocol',
  },
  [RESOURCES.TRANSPORT_PROTOCOLS]: {
    'transport-protocols': 'transport-protocols',
  },
  [RESOURCES.ACCOUNTS]: {
    name: '',
    balance: '',
    'min-balance': '',
    'max-balance': '',
    'destination-rate-limit': '',
    'origination-capacity': '',
    'termination-capacity': '',
    'total-capacity': '',
  },
  [RESOURCES.NETWORKS]: {
    name: '',
    'network-type': {
      jsonApi: 'hasOne',
      type: 'network-type',
      name: '',
    },
  },
  [RESOURCES.NETWORK_TYPES]: {
    name: '',
  },
  [RESOURCES.ACTIVE_CALLS]: {
    'from-time': '',
    'to-time': '',
    account: {
      jsonApi: 'hasOne',
      type: 'accounts',
      id: '',
    },
    terminatedCalls: {
      jsonApi: 'hasMany',
      x: null,
      y: '',
    },
    originatedCalls: {
      jsonApi: 'hasMany',
      x: null,
      y: '',
    },
  },
  [RESOURCES.INVOICES]: {
    amount: '',
    'billing-duration': '',
    'calls-count': '',
    'calls-duration': '',
    'end-date': '',
    'first-call-at': '',
    'first-successful-call-at': '',
    'has-pdf': '',
    'last-call-at': '',
    'last-successful-call-at': '',
    reference: '',
    'start-date': '',
    'successful-calls-count': '',
    account: {
      jsonApi: 'hasOne',
      type: 'accounts',
      id: '',
    },
  },
  [RESOURCES.ORIGINATED_CPS]: {
    'from-time': '',
    'to-time': '',
    account: {
      jsonApi: 'hasOne',
      type: 'accounts',
      id: '',
    },
    cps: {
      jsonApi: 'hasMany',
      x: null,
      y: '',
    },
  },
};
